main: com.huxiaoheng.MyPlugun
name: Myplugin
version: 1.0.0
author: huxiaoheng
commands:
  show:
    description: "显示玩家的一些信息"
    aliases: ['zhanshi','xianshi']
    usage: "Usage /show name|money|location"
  cheat:
    description: "use for cheat"
    aliases: zuobi
    usage: "Usage /cheat fly|recover|..."